apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Prajwalkadam29/gitops-config-cc-app.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{.path.basename}}-dev'
    spec:
      project: default
      source:
        repoURL: https://github.com/Prajwalkadam29/gitops-config-cc-app.git
        targetRevision: main
        path: '{{.path.path}}/helm'
        helm:
          valueFiles:
            - values.yaml
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}-dev'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true