apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Prajwalkadam29/gitops-config-cc-app.git
              revision: main
              directories:
                - path: apps/*
          - list:
              elements:
                - env: dev
                - env: staging
                - env: prod
  template:
    metadata:
      # Removed leading dots
      name: '{{path.basename}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Prajwalkadam29/gitops-config-cc-app.git
        targetRevision: main
        # Removed leading dots
        path: '{{path}}/helm'
        helm:
          valueFiles:
            - values.yaml
            # Removed leading dot
            - 'values-{{env}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        # Removed leading dots
        namespace: '{{path.basename}}-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true