apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-api-secret
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: "1h"
  # This references a ClusterSecretStore (configured in your cluster) that holds the AWS IAM permissions
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    # This is the name of the Kubernetes Secret that will be created dynamically
    name: {{ .Release.Name }}-api-secret-k8s
    creationPolicy: Owner
  data:
    # 1. The name of the key inside the newly created Kubernetes Secret
    - secretKey: CURRENCY_API_KEY
      remoteRef:
        # 2. The exact name of your secret in AWS Secrets Manager
        key: {{ .Values.externalSecrets.awsSecretName }}
        # 3. The JSON key inside that AWS Secret that holds the actual API key string
        property: {{ .Values.externalSecrets.awsSecretProperty }}